paths:
  /api/products/:
    get:
      summary: Obtener los productos
      tags:
        - Productos
      responses:
        "200":
          description: Todos los productos obtenidos exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "401":
          description: Error faltan permisos
        "500":
          description: Error interno
    post:
      summary: Crear un producto
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/productModel'
      responses:
        "200":
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno
  /api/products/{pid}:
    get:
      summary: Obtener un producto por el id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: pid es el id del producto para obtener
          schema:
            $type: string
      responses:
        "200":
          description: Se obtuvo el producto exitosamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "500":
          description: Error interno
    put:
      summary: Actualizar un producto obtenido por su id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: pid es el id del producto que desea
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/productModel'
      responses:
        "200":
          description: Se actualizo el producto exitoisamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "500":
          description: Error interno
    delete:
      summary: Eliminar un producto segun su id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: pid es el id del producto a eliminar
          schema:
            $type: string
      responses:
        "200":
          description: Se elimino el producto correctamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "500":
          description: Error interno 

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: id del producto generado por database
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        category:
          type: String
          description: Categoria del producto
        price:
          type: Number
          description: Precio del producto
        img:
          type: String
          description: Imagen del producto
        status:
          type: boolean
          description: Status del producto
        code:
          type: String
          description: Codigo unico del producto
        stock:
          type: Number
          description: Cantidad en stock del producto
      example:
        _id: ObjectId('nkjs23123521')
        example:
        title: J. WALKER
        description: Whisky Reserve Black Label
        category: Whisky
        price: 12000
        img: http://www.whisky.com/jwalker
        status: true
        code: KLSJU239123
        stock: 35
  requestBodies:
    productModel:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        category:
          type: String
          description: Categoria del producto
        price:
          type: Number
          description: Precio del producto
        img:
          type: String
          description: Imagen del producto
        code:
          type: String
          description: Codigo unico del producto
        stock:
          type: Number
          description: Cantidad en stock del producto
      example:
        title: J. WALKER
        description: Whisky Reserve Black Label
        category: Whisky
        price: 12000
        img: http://www.whisky.com/jwalker
        status: true
        code: KLSJU239123
        stock: 35